import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { EmptyState } from "@/components/ui/empty-state";
import { PriorityBadge, SlaBadge, TicketStatusBadge } from "@/components/ui/badge";
import type { TicketSummary } from "@/lib/types";
import { formatDate } from "@/lib/utils";

export function TicketTable({ tickets, basePath }: { tickets: TicketSummary[]; basePath: string }) {
  if (!tickets.length) return <EmptyState title="No tickets found" description="Try changing the filters or create a new ticket." />;
  return <div className="overflow-hidden rounded-2xl border border-white/80 bg-white/90 shadow-[0_12px_40px_rgba(15,23,42,0.07)] backdrop-blur">
    <div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-semibold text-slate-900">Ticket queue</h2><p className="mt-0.5 text-xs text-slate-500">{tickets.length} shown on this page</p></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-emerald-700"><span className="mr-1.5 inline-block h-1.5 w-1.5 rounded-full bg-emerald-500" />Synced</span></div>
    <div className="overflow-x-auto"><table className="min-w-full"><thead><tr className="border-b border-slate-100 bg-slate-50/60">{["Ticket", "Customer", "Status", "Priority", "Assigned", "SLA", "Created", ""].map((heading) => <th key={heading} className="whitespace-nowrap px-5 py-3 text-left text-[10px] font-bold uppercase tracking-[0.12em] text-slate-400">{heading}</th>)}</tr></thead>
      <tbody className="divide-y divide-slate-100">{tickets.map((ticket) => { const customer = ticket.customer?.full_name ?? "Unknown"; const initials = customer.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase(); return <tr key={ticket.id} className="group transition hover:bg-indigo-50/35"><td className="max-w-sm px-5 py-4"><Link className="block font-semibold text-slate-900 transition group-hover:text-indigo-700" href={`${basePath}/${ticket.id}`}>{ticket.title}</Link><p className="mt-1 text-[11px] font-medium capitalize text-slate-400">#{ticket.id.slice(0, 8)} · {ticket.category}</p></td><td className="whitespace-nowrap px-5 py-4"><div className="flex items-center gap-2.5"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-slate-100 to-indigo-100 text-[10px] font-bold text-indigo-700">{initials}</span><span className="text-sm font-medium text-slate-600">{customer}</span></div></td><td className="px-5 py-4"><TicketStatusBadge status={ticket.status} /></td><td className="px-5 py-4"><PriorityBadge priority={ticket.priority} /></td><td className="whitespace-nowrap px-5 py-4 text-sm text-slate-600">{ticket.agent?.full_name ?? <span className="text-slate-400">Unassigned</span>}</td><td className="whitespace-nowrap px-5 py-4"><SlaBadge dueAt={ticket.response_due_at} responseAt={ticket.first_agent_response_at} /></td><td className="whitespace-nowrap px-5 py-4 text-xs text-slate-500">{formatDate(ticket.created_at)}</td><td className="px-5 py-4"><Link aria-label={`Open ${ticket.title}`} href={`${basePath}/${ticket.id}`} className="flex h-8 w-8 items-center justify-center rounded-lg text-slate-400 transition group-hover:bg-white group-hover:text-indigo-600 group-hover:shadow-sm"><ArrowUpRight className="h-4 w-4" /></Link></td></tr>; })}</tbody>
    </table></div>
  </div>;
}
