import { createClient } from "@/lib/supabase/server";
import type { CurrentMember, TicketSummary } from "@/lib/types";
import type { TicketFilters } from "@/lib/tickets/filters";

export async function getTickets(member:CurrentMember, filters:TicketFilters, limit=20){ const supabase=await createClient(); const from=(filters.page-1)*limit; let query=supabase.from("tickets").select("id,title,category,priority,status,response_due_at,first_agent_response_at,created_at,created_by,assigned_agent_id,customer:profiles!tickets_created_by_fkey(full_name),agent:profiles!tickets_assigned_agent_id_fkey(full_name)",{count:"exact"}).order("created_at",{ascending:false}).range(from,from+limit-1); if(filters.q) query=query.ilike("title",`%${filters.q.replaceAll("%","")}%`); if(filters.status) query=query.eq("status",filters.status); if(filters.priority) query=query.eq("priority",filters.priority); if(filters.category) query=query.eq("category",filters.category); if(filters.agent) query=query.eq("assigned_agent_id",filters.agent); if(filters.view==="mine") query=query.eq("assigned_agent_id",member.userId); if(filters.view==="unassigned") query=query.is("assigned_agent_id",null); const {data,error,count}=await query; if(error) throw new Error("Unable to load tickets"); return {tickets:(data??[]) as unknown as TicketSummary[],count:count??0}; }

export async function getTicket(ticketId:string){ const supabase=await createClient(); const {data,error}=await supabase.from("tickets").select("*,customer:profiles!tickets_created_by_fkey(full_name),agent:profiles!tickets_assigned_agent_id_fkey(full_name)").eq("id",ticketId).maybeSingle(); if(error||!data) return null; const [{data:comments},{data:attachments},{data:events}]=await Promise.all([supabase.from("comments").select("*,author:profiles!comments_author_id_fkey(full_name)").eq("ticket_id",ticketId).order("created_at"),supabase.from("attachments").select("*").eq("ticket_id",ticketId).order("created_at"),supabase.from("ticket_events").select("*,actor:profiles!ticket_events_actor_id_fkey(full_name)").eq("ticket_id",ticketId).order("created_at",{ascending:false})]); return {...data,customer:data.customer as unknown as {full_name:string}|null,agent:data.agent as unknown as {full_name:string}|null,comments:comments??[],attachments:attachments??[],events:events??[]}; }

export async function getAgents(){ const supabase=await createClient(); const {data}=await supabase.from("organization_members").select("user_id,is_active,profiles(full_name)").eq("role","agent").eq("is_active",true); return (data??[]).map((item)=>({id:item.user_id,name:(item.profiles as unknown as {full_name:string}|null)?.full_name??"Agent"})); }

export interface DashboardStats { open:number; inProgress:number; resolved:number; closed:number; overdue:number; myAssigned:number; myOpen:number; myOverdue:number; unassigned:number; byStatus:Record<string,number>; byPriority:Record<string,number> }
export async function getDashboardStats(){ const supabase=await createClient(); const {data,error}=await supabase.rpc("get_dashboard_stats"); if(error) throw new Error("Unable to load dashboard"); return data as unknown as DashboardStats; }
